### PR TITLE
bug fix for checking ges_z allocation status

### PR DESCRIPTION
**Pull request by ShunLiu-NOAA**
bug fix for checking ges_z allocation status

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@ShunLiu-NOAA there are a lot more changes here than I expected and I'm not sure why. I see things that "changed" but based on both branches, they should be the same. Also there are merge conflicts.

**Comment by CoryMartin-NOAA** [comment]
Let me start by updating my branch to GSI v16 most recent version and see if that makes any difference.

**Comment by ShunLiu-NOAA** [comment]
[image: image.png]

**Comment by ShunLiu-NOAA** [comment]
I am trying to merge to your feature/jedi_gfsv16 branch.

Shun

**Pull request closed without merging**
